/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  language?: "pt" | "en";
  translationKey?: string;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
  >;
  publishedAt?: string;
  tags?: Array<string>;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: POSTS_BY_LANG_QUERY
// Query: *[_type == "post" && language == $lang && defined(slug.current)]  | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    tags,    featured,    publishedAt,    translationKey  }
export type POSTS_BY_LANG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  tags: Array<string> | null;
  featured: boolean | null;
  publishedAt: string | null;
  translationKey: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && language == $lang && slug.current == $slug][0]{    _id,    title,    excerpt,    publishedAt,    tags,    translationKey,    language,    "slug": slug.current,    coverImage{      alt,      hotspot,      crop,      asset,      "lqip": asset->metadata.lqip,      "dimensions": asset->metadata.dimensions    },    body[]{      ...,      _type == "image" => {        alt,        hotspot,        crop,        asset,        "lqip": asset->metadata.lqip,        "dimensions": asset->metadata.dimensions      }    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  translationKey: string | null;
  language: "en" | "pt" | null;
  slug: string | null;
  coverImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: SanityImageAssetReference | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        _type: "image";
        _key: string;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      }
  > | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_TRANSLATION_QUERY
// Query: *[_type == "post" && translationKey == $translationKey && language != $language][0]{    "slug": slug.current,    language  }
export type POST_TRANSLATION_QUERY_RESULT = {
  slug: string | null;
  language: "en" | "pt" | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: TRANSLATED_SLUG_QUERY
// Query: *[_type == "post" && language == $lang && slug.current == $slug][0]{    "target": *[_type == "post" && language == $targetLang && translationKey == ^.translationKey][0].slug.current  }.target
export type TRANSLATED_SLUG_QUERY_RESULT = string | null;

// Source: ../web/src/sanity/queries.ts
// Variable: POSTS_BY_TAG_QUERY
// Query: *[_type == "post" && language == $lang && $tagName in tags]  | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    tags,    featured,    publishedAt,    translationKey  }
export type POSTS_BY_TAG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  tags: Array<string> | null;
  featured: boolean | null;
  publishedAt: string | null;
  translationKey: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: RSS_POSTS_QUERY
// Query: *[_type == "post" && language == $lang && defined(slug.current)]  | order(publishedAt desc) [0...20] {    title,    excerpt,    "slug": slug.current,    publishedAt  }
export type RSS_POSTS_QUERY_RESULT = Array<{
  title: string | null;
  excerpt: string | null;
  slug: string | null;
  publishedAt: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: SITEMAP_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(publishedAt desc) {    "slug": slug.current,    language,    publishedAt  }
export type SITEMAP_POSTS_QUERY_RESULT = Array<{
  slug: string | null;
  language: "en" | "pt" | null;
  publishedAt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && language == $lang && defined(slug.current)]\n  | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    tags,\n    featured,\n    publishedAt,\n    translationKey\n  }\n': POSTS_BY_LANG_QUERY_RESULT;
    '\n  *[_type == "post" && language == $lang && slug.current == $slug][0]{\n    _id,\n    title,\n    excerpt,\n    publishedAt,\n    tags,\n    translationKey,\n    language,\n    "slug": slug.current,\n    coverImage{\n      alt,\n      hotspot,\n      crop,\n      asset,\n      "lqip": asset->metadata.lqip,\n      "dimensions": asset->metadata.dimensions\n    },\n    body[]{\n      ...,\n      _type == "image" => {\n        alt,\n        hotspot,\n        crop,\n        asset,\n        "lqip": asset->metadata.lqip,\n        "dimensions": asset->metadata.dimensions\n      }\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && translationKey == $translationKey && language != $language][0]{\n    "slug": slug.current,\n    language\n  }\n': POST_TRANSLATION_QUERY_RESULT;
    '\n  *[_type == "post" && language == $lang && slug.current == $slug][0]{\n    "target": *[_type == "post" && language == $targetLang && translationKey == ^.translationKey][0].slug.current\n  }.target\n': TRANSLATED_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && language == $lang && $tagName in tags]\n  | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    tags,\n    featured,\n    publishedAt,\n    translationKey\n  }\n': POSTS_BY_TAG_QUERY_RESULT;
    '\n  *[_type == "post" && language == $lang && defined(slug.current)]\n  | order(publishedAt desc) [0...20] {\n    title,\n    excerpt,\n    "slug": slug.current,\n    publishedAt\n  }\n': RSS_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(publishedAt desc) {\n    "slug": slug.current,\n    language,\n    publishedAt\n  }\n': SITEMAP_POSTS_QUERY_RESULT;
  }
}
